-- Only these leaves are managed; credentials, identity and per-book state are not.
return {
-- Without this marker, BookOrbit migrates a newly created table back to defaults.
-- Seed it only when absent; never downgrade an existing schema marker.
seed = { bookorbit = { settings_version = 1 } },
set = {
    cre_font = "Bookerly", -- Provision with scripts/fonts.py fetch and install; binaries stay out of Git.
    copt_font_size = 17,
    copt_line_spacing = 110,
    copt_embedded_fonts = 0,
    copt_font_base_weight = 0.5,
    copt_h_page_margins = { 30, 30 },
    copt_t_page_margin = 20,
    copt_smooth_scaling = 1,
    copt_word_expansion = 0,
    footnote_link_in_popup = true,
    default_highlight_action = "ask",
    highlight_dialog_position = "center",
    highlight_lighten_factor = 0.2,
    screensaver_type = "cover",
    screensaver_show_message = false,
    screensaver_stretch_images = false,
    screensaver_img_background = "black",
    style_tweaks = {
        font_size_most_reset = true,
        ["footnote-inpage_epub"] = true,
        ["footnote-inpage_fb2"] = true,
        ["inpage_footnote_font-size_smaller"] = true,
        lineheight_all_inherit = true,
        lineheight_all_normal_strut_confined = true,
        margin_body_0 = true,
        sub_sup_smaller = true,
        widows_orphans_avoid = true,
    },
    footer = {
        disabled = false, all_at_once = true, align = "center",
        percentage = true, pages_left = true,
        chapter_time_to_read = true, book_time_to_read = true,
        disable_progress_bar = false, toc_markers = true,
        progress_bar_position = "alongside", progress_bar_min_width_pct = 20,
        pages_left_includes_current_page = false,
        time = false, battery = false, frontlight = false, wifi_status = false,
        book_title = false, book_author = false, book_chapter = false,
        bookmark_count = false, chapter_progress = false, chapter_progress_bar = false,
        pages_left_book = false, page_progress = false, mem_usage = false,
        page_turning_inverted = false,
        item_prefix = "icons", items_separator = "bar",
        text_font_face = "./fonts/noto/NotoSans-Regular.ttf",
        text_font_size = 14, text_font_bold = false,
        container_height = 14, container_bottom_padding = 1,
        order = {
            [0] = "off", "pages_left_book", "time", "percentage", "pages_left",
            "chapter_time_to_read", "book_time_to_read", "page_progress", "battery",
            "frontlight", "mem_usage", "wifi_status", "book_title", "book_chapter",
            "bookmark_count", "chapter_progress", "frontlight_warmth", "custom_text",
            "book_author", "page_turning_inverted", "dynamic_filler", "additional_content",
        },
    },
    statistics = { is_enabled = true, min_sec = 5, max_sec = 180 },
    bookorbit = {
        auto_sync = false, annotation_sync = true, pages_before_update = 10,
        catalog_grid_cols = 4, catalog_grid_rows = 3,
        catalog_mosaic_show_titles = false, catalog_sort = "recently_added",
    },
} }
